// src/components/RestartDialog.tsx
import { useEffect, useState } from "react";
import type { UnlistenFn } from "@tauri-apps/api/event";
import { events, zcode } from "../api";
import { toast } from "./Toast";

/** 全局重启确认弹窗：监听后端 zcode://restart-requested，确认后重启 zcode */
export function RestartDialog() {
  const [reason, setReason] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    let un: UnlistenFn | undefined;
    events.onRestartRequested((p) => setReason(p.reason)).then((fn) => (un = fn));
    return () => un?.();
  }, []);

  if (!reason) return null;

  const confirm = async () => {
    setBusy(true);
    try {
      await zcode.restartZcode();
      setReason(null);
    } catch (e: unknown) {
      toast.error(typeof e === "string" ? e : "重启失败");
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="rd-overlay">
      <div className="za-glass-strong rd-card">
        <strong>需要重启 zcode 生效</strong>
        <p className="za-muted" style={{ fontSize: "var(--fs-sm)", margin: 0 }}>
          {reason}
        </p>
        <div
          className="za-row"
          style={{ justifyContent: "flex-end", gap: 8, marginTop: 10 }}
        >
          <button
            className="za-btn za-btn-sm"
            disabled={busy}
            onClick={() => setReason(null)}
          >
            稍后
          </button>
          <button
            className="za-btn za-btn-sm za-btn-primary"
            disabled={busy}
            onClick={confirm}
          >
            {busy ? "重启中…" : "立即重启"}
          </button>
        </div>
      </div>
    </div>
  );
}

// src/components/RestartDialog.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { MyDialog } from 'myui'
import { events, zcode } from '@/api'
import { toast } from '@/composables/toast'

/** 全局重启确认弹窗：监听后端 zcode://restart-requested，确认后重启 zcode */
defineOptions({ name: 'RestartDialog' })

const reason = ref<string | null>(null)
const busy = ref(false)
let un: (() => void) | undefined

onMounted(() => {
  events.onRestartRequested((p) => (reason.value = p.reason)).then((fn) => (un = fn))
})
onBeforeUnmount(() => un?.())

async function confirm(): Promise<void> {
  busy.value = true
  try {
    await zcode.restartZcode()
    reason.value = null
  } catch (e: unknown) {
    toast.error(typeof e === 'string' ? e : '重启失败')
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <MyDialog
    :model-value="reason != null"
    title="需要重启 zcode 生效"
    :width="380"
    cancel-text="稍后"
    :confirm-text="busy ? '重启中…' : '立即重启'"
    :confirm-loading="busy"
    manual-close
    @cancel="reason = null"
    @confirm="confirm"
  >
    <p class="rd-reason">{{ reason }}</p>
  </MyDialog>
</template>

<style scoped>
.rd-reason {
  margin: 0;
  color: var(--text-secondary);
  font-size: 12px;
  line-height: 1.7;
}
</style>
